[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "HHHLVvTBydJjYBvonpoQX5cA1upVe6dixwwiYPQFmtbi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/tom/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
