[features]
seeds = false
skip-lint = false
[programs.localnet]
overflow_underflow = "7Bce37n1XhVnk7Ei83mg9r2svVmwyZJiMBd86DqJJWr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tom/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
